### ISSUE TITLE
__archive_fetch is missing in 0.9.15

### ISSUE THREAD

**Issue by hamsterready** [graphite-project/whisper#171]
Hi guys,

When I try to run whisper-diff I got:
```
Traceback (most recent call last):
  File "/usr/local/bin/whisper-diff.py", line 59, in <module>
    archive_diffs = whisper.diff(path_a,path_b,ignore_empty=options.ignore_empty)
  File "/usr/local/lib/python2.7/dist-packages/whisper.py", line 848, in diff
    diffs = file_diff(fh_from, fh_to, ignore_empty)
  File "/usr/local/lib/python2.7/dist-packages/whisper.py", line 871, in file_diff
    (fromTimeInfo, fromValues) = __archive_fetch(fh_from, archive, startTime, untilTime)
NameError: global name '__archive_fetch' is not defined

```

And it seems that __archive_fetch is missing in https://github.com/graphite-project/whisper/blob/0.9.15/whisper.py for some reason.

My config:

```
2016-06-30 14:41:28 root@p2:/usr/local/lib/python2.7/dist-packages# pip show whisper
---
Metadata-Version: 2.0
Name: whisper
Version: 0.9.15
Summary: Fixed size round-robin style database
Home-page: http://graphite-project.github.com/
Author: Chris Davis
Author-email: chrismd@gmail.com
Installer: pip
License: Apache Software License 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
Classifiers:
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
2016-06-30 14:41:34 root@p2:/usr/local/lib/python2.7/dist-packages# cat /usr/local/lib/python2.7/dist-packages/whisper.py | grep __archive_fetch
    (fromTimeInfo, fromValues) = __archive_fetch(fh_from, archive, startTime, untilTime)
    (toTimeInfo, toValues) = __archive_fetch(fh_to, archive, startTime, untilTime)

```

BTW, __archive_fetch is present in master.

**Comment by hamsterready** [comment]
For the record, if you copy and paste __archive_fetch from master into 0.9.15/whisper.py diff works as it should.

**Comment by deniszh** [comment]
Yep, yo're right - I backported whisper-diff.py to 0.9.15, but forgot to backport __archive_fetch...
Could you please create PR for that?
Or I will do it but later....
