### ISSUE TITLE
Make errors in retention config more verbose 

### ISSUE THREAD

**Issue by msoedov** [graphite-project/whisper#180]
It would be nice to see the line and string value that caused an error of configuration parsing

```
Traceback (most recent call last):
  File "/opt/graphite/bin/carbon-cache.py", line 32, in <module>
    run_twistd_plugin(__file__)
  File "/opt/graphite/lib/carbon/util.py", line 96, in run_twistd_plugin
    runApp(config)
  File "/usr/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in runApp
Starting carbon-cache (instance a)
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 386, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/site-packages/twisted/application/app.py", line 446, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/opt/graphite/lib/twisted/plugins/carbon_cache_plugin.py", line 21, in makeService
    return service.createCacheService(options)
  File "/opt/graphite/lib/carbon/service.py", line 126, in createCacheService
    from carbon.writer import WriterService
  File "/opt/graphite/lib/carbon/writer.py", line 33, in <module>
    SCHEMAS = loadStorageSchemas()
  File "/opt/graphite/lib/carbon/storage.py", line 126, in loadStorageSchemas
    archives = [Archive.fromString(s) for s in retentions]
  File "/opt/graphite/lib/carbon/storage.py", line 110, in fromString
    (secondsPerPoint, points) = whisper.parseRetentionDef(retentionDef)
  File "/usr/local/lib/python2.7/site-packages/whisper.py", line 122, in parseRetentionDef
    (precision, points) = retentionDef.strip().split(':')
ValueError: too many values to unpack
```

**Comment by piotr1212** [comment]
I think this is improved in https://github.com/graphite-project/whisper/pull/200
carbon should handle the exception to print prettier
