### ISSUE TITLE
importing whisper from python console failled 

### ISSUE THREAD

**Issue by pidou46** [graphite-project/whisper#288]
Windows 10
Python 3.7.3

`>>> import whisper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Python3\Lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "E:\Python3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
>>> exit
Use exit() or Ctrl-Z plus Return to exit
>>> eit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'eit' is not defined`

**Comment by deniszh** [comment]
Hi @pidou46 ,

Sorry,  Windows never was supported platform for Whisper/Graphite.
