### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by gcommit** [graphite-project/whisper#315]
Hello,

when i try to install whisper in my dockerfile, what was working for months - is not working anymore. See below. Can you help me here?

```
root@70d501555a68:/# pip install --no-binary=:all: https://github.com/graphite-project/whisper/tarball/1.1.8
Collecting https://github.com/graphite-project/whisper/tarball/1.1.8
  Downloading https://github.com/graphite-project/whisper/tarball/1.1.8
     - 51kB 3.6MB/s
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from whisper==1.1.8)
Installing collected packages: whisper
  Running setup.py install for whisper ... done
Successfully installed whisper-1.1.8
root@70d501555a68:/# pip install --no-binary=:all: https://github.com/graphite-project/carbon/tarball/1.1.8
Collecting https://github.com/graphite-project/carbon/tarball/1.1.8
  Downloading https://github.com/graphite-project/carbon/tarball/1.1.8
     - 133kB 5.2MB/s
Collecting Twisted (from carbon==1.1.8)
  Downloading https://files.pythonhosted.org/packages/4a/b4/4973c7ccb5be2ec0abc779b7d5f9d5f24b17b0349e23240cfc9dc3bd83cc/Twisted-20.3.0.tar.bz2 (3.1MB)
    100% |################################| 3.1MB 365kB/s
Collecting cachetools (from carbon==1.1.8)
  Downloading https://files.pythonhosted.org/packages/ae/37/7fd45996b19200e0cb2027a0b6bef4636951c4ea111bfad36c71287247f6/cachetools-3.1.1.tar.gz
Collecting txAMQP (from carbon==1.1.8)
  Downloading https://files.pythonhosted.org/packages/c6/a0/7c18f4a3805af57e2be19a6502c1946f5dac51c8b1ed19368968a46a2f07/txAMQP-0.8.2.tar.gz
Requirement already satisfied: urllib3 in /usr/lib/python2.7/dist-packages (from carbon==1.1.8)
Collecting Automat>=0.3.0 (from Twisted->carbon==1.1.8)
  Downloading https://files.pythonhosted.org/packages/80/c5/82c63bad570f4ef745cc5c2f0713c8eddcd07153b4bee7f72a8dc9f9384b/Automat-20.2.0.tar.gz (61kB)
    100% |################################| 71kB 6.2MB/s
    Complete output from command python setup.py egg_info:
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'


    !!! m2r not found, long_description is bad, don't upload this to PyPI !!!



    Installed /tmp/pip-build-3FgRzQ/Automat/.eggs/m2r-0.2.1-py2.7.egg
    Searching for setuptools-scm
    Reading https://pypi.python.org/simple/setuptools-scm/
    Downloading https://files.pythonhosted.org/packages/57/38/930b1241372a9f266a7df2b184fb9d4f497c2cef2e016b014f82f541fe7c/setuptools_scm-6.0.1.tar.gz#sha256=d1925a69cb07e9b29416a275b9fadb009a23c148ace905b2fb220649a6c18e92
    Best match: setuptools-scm 6.0.1
    Processing setuptools_scm-6.0.1.tar.gz
    Writing /tmp/easy_install-HJwx1Q/setuptools_scm-6.0.1/setup.cfg
    Running setuptools_scm-6.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-HJwx1Q/setuptools_scm-6.0.1/egg-dist-tmp-fwKiaB
    /tmp/easy_install-HJwx1Q/setuptools_scm-6.0.1/src
    <pkg_resources.WorkingSet object at 0x7fa1fb9f2d10>
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3FgRzQ/Automat/setup.py", line 58, in <module>
        'Programming Language :: Python :: 3.8',
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1163, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-HJwx1Q/setuptools_scm-6.0.1/setup.py", line 52, in <module>
        'Programming Language :: Python :: 2',
      File "/tmp/easy_install-HJwx1Q/setuptools_scm-6.0.1/setup.py", line 29, in scm_config
        install_requires=[
      File "/tmp/easy_install-HJwx1Q/setuptools_scm-6.0.1/src/setuptools_scm/__init__.py", line 8, in <module>
      File "/tmp/easy_install-HJwx1Q/setuptools_scm-6.0.1/src/setuptools_scm/config.py", line 6, in <module>
      File "/tmp/easy_install-HJwx1Q/setuptools_scm-6.0.1/src/setuptools_scm/utils.py", line 41
        print(*k)
              ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3FgRzQ/Automat/
```

**Comment by deniszh** [comment]
Hi @gcommit 
Some modules are incompatible with your python or libraries.
Try to pin Automat to <= 0.8.0
```
pip install Automat==0.8.0
pip install --no-binary=:all: https://github.com/graphite-project/carbon/tarball/1.1.8
```

**Comment by gcommit** [comment]
Thanks. Worked. Now it fails at this step:

`RUN PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb`
with

```
 > [19/71] RUN PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb:
#23 0.561 Could not import graphite.local_settings, using defaults!
#23 0.588 /opt/graphite/webapp/graphite/settings.py:356: UserWarning: SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security
#23 0.588   warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')
#23 0.652 Traceback (most recent call last):
#23 0.652   File "/usr/local/bin/django-admin.py", line 5, in <module>
#23 0.652     management.execute_from_command_line()
#23 0.652   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
#23 0.652     utility.execute()
#23 0.652   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute
#23 0.652     django.setup()
#23 0.653   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
#23 0.653     apps.populate(settings.INSTALLED_APPS)
#23 0.653   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
#23 0.653     app_config = AppConfig.create(entry)
#23 0.653   File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 127, in create
#23 0.653     import_module(entry)
#23 0.653   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
#23 0.653     __import__(name)
#23 0.653   File "/opt/graphite/webapp/graphite/functions/__init__.py", line 9, in <module>
#23 0.653     from graphite.functions.params import Param, ParamTypes, ParamTypeAggFunc  # noqa
#23 0.653   File "/opt/graphite/webapp/graphite/functions/params.py", line 7, in <module>
#23 0.653     from graphite.render.datalib import TimeSeries
#23 0.654   File "/opt/graphite/webapp/graphite/render/datalib.py", line 25, in <module>
#23 0.654     from graphite.storage import STORE
#23 0.654   File "/opt/graphite/webapp/graphite/storage.py", line 30, in <module>
#23 0.654     from graphite.render.grammar import grammar
#23 0.654   File "/opt/graphite/webapp/graphite/render/grammar.py", line 3, in <module>
#23 0.654     from graphite.render.grammar_unsafe import grammar as _grammar
#23 0.654   File "/opt/graphite/webapp/graphite/render/grammar_unsafe.py", line 1, in <module>
#23 0.654     from pyparsing import (
#23 0.654 ImportError: cannot import name pyparsing_unicode
------
executor failed running [/bin/sh -c PYTHONPATH=/opt/graphite/webapp django-admin.py migrate --settings=graphite.settings --run-syncdb]: exit code: 1
```

**Comment by deniszh** [comment]
Looks like more and more modules dropping pyhon 2 support. Downgrade pyparsing to 2.4.7:
```
pip install pyparsing==2.4.7
```
