### ISSUE TITLE
TypeError: fetch() takes at most 3 arguments (4 given)

### ISSUE THREAD

**Issue by zrowe** [graphite-project/whisper#67]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "./graphite/render/views.py", line 112, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "./graphite/render/evaluator.py", line 10, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "./graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "./graphite/render/evaluator.py", line 24, in evaluateTokens
    return fetchData(requestContext, tokens.pathExpression)
  File "./graphite/render/datalib.py", line 230, in fetchData
    dbResults = dbFile.fetch( timestamp(startTime), timestamp(endTime), timestamp(now))
  File "./graphite/storage.py", line 308, in fetch
    return whisper.fetch(self.fs_path, startTime, endTime, now)
TypeError: fetch() takes at most 3 arguments (4 given)
```

using whisper 0.9.12

**Comment by bellaweo** [comment]
Hi there. just encountered this exact error a year later. And the fix above resolved it. Any updates on pypi versions of graphite-web & whisper?
