### ISSUE TITLE
contrib/whisper-auto-resize.py fails

### ISSUE THREAD

**Issue by JensRantil** [graphite-project/whisper#96]
```
# python whisper-auto-resize.py /archive2/graphite/ /etc/carbon/
Traceback (most recent call last):
  File "whisper-auto-resize.py", line 208, in <module>
    processMetric(fullpath, schemas, agg_schemas)
  File "whisper-auto-resize.py", line 136, in processMetric
    str_xFilesFactor =  "{0:.2f}".format(xFilesFactor)
ValueError: Unknown format code 'f' for object of type 'str'
# python -V
Python 2.7.3
# dpkg -l|grep carbon
ii  graphite-carbon                   0.9.10-1                      backend data caching and persistence daemon for Graphite
```

**Comment by nicktgr15** [comment]
I came across the same issue on centos 6

```
$ ./whisper-auto-resize.py /var/lib/carbon/whisper/ /etc/carbon/
Traceback (most recent call last):
  File "./whisper-auto-resize.py", line 207, in <module>
    processMetric(fullpath, schemas, agg_schemas)
  File "./whisper-auto-resize.py", line 135, in processMetric
    str_xFilesFactor =  "{0:.2f}".format(xFilesFactor)
ValueError: Unknown format code 'f' for object of type 'str'
```
```
$ python -V
Python 2.6.6
```

```
Name        : python-carbon 
Version     : 0.9.12

Name        : python-whisper 
Version     : 0.9.12
```

**Comment by zzl0** [comment]
Some thing wrong here https://github.com/graphite-project/carbon/blob/master/lib/carbon/storage.py#L168 .

    h[33] >>> "{0:.2f}".format(None)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ValueError: Unknown format code 'f' for object of type 'str'

You may need to check your aggregation config file.

**Comment by toni-moreno** [comment]
I've fixed with Python 2.4.3

By only changing these two lines.

```

    #info_xFilesFactor = "{0:.2f}".format(info['xFilesFactor'])
    info_xFilesFactor = '{0:%(x).2f}' % { "x" : info['xFilesFactor'] }
    #str_xFilesFactor =  "{0:.2f}".format(xFilesFactor)
    str_xFilesFactor =  '{0:%(x).2f}' % { "x" : xFilesFactor }
```

**Comment by N-Mi** [comment]
I can confirm this fixes the issue.

**Comment by deniszh** [comment]
https://github.com/graphite-project/whisper/pull/174 should fix that

**Comment by deniszh** [comment]
Fix is merged
